name = "memenow-storage-cf-workers"
main = "build/worker/shim.mjs"
compatibility_date = "2025-08-15"
logpush = true

[placement]
mode = "smart"

[build]
command = "cargo install -q worker-build && worker-build --release"

[[r2_buckets]]
binding = "STORAGE_BUCKET"
bucket_name = "xxxx"
preview_bucket_name = "xxxx"

[[kv_namespaces]]
binding = "STORAGE_CONFIG"
id = "your-production-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"

[[d1_databases]]
binding = "UPLOAD_DB"
database_name = "xxxx"
database_id = "your-prod-d1-database-id"
preview_database_id = "your-dev-d1-database-id"

[observability.logs]
enabled = true