name: Deploy Worker
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Install worker-build
        run: cargo install worker-build
      - name: Generate wrangler.toml
        run: |
          echo "${{ secrets.WRANGLER_TOML_TEMPLATE }}" > wrangler.toml
          sed -i 's/your-production-bucket-name/${{ secrets.PRD_R2_BUCKET }}/g' wrangler.toml
          sed -i 's/your-preview-bucket-name/${{ secrets.DEV_R2_BUCKET }}/g' wrangler.toml
          sed -i 's/your-production-kv-namespace-id/${{ secrets.PRD_KV_NAMESPACE_ID }}/g' wrangler.toml
          sed -i 's/your-preview-kv-namespace-id/${{ secrets.DEV_KV_NAMESPACE_ID }}/g' wrangler.toml
      - name: Build & Deploy Worker
        run: |
          cargo build --release --target wasm32-unknown-unknown
          wrangler publish --config wrangler.toml
        env:
          CF_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
